### ISSUE TITLE
Set a maximum amount of money someone can send.

### ISSUE THREAD

**Issue by R13N** [ZeusWPI/Tab#12]

**Comment by iasoon** [comment]
How much should this amount be? Should this limit be in effect for admins as well?

**Comment by R13N** [comment]
The reason why this issue was created is because it it possible to create a transaction of € 9999999.00, I suggest setting a hard cap of 500 for all users.

Maybe there should be popup that asks for confirmation above a certain amount? I.e. "Are you sure you want to send € X to Y?". Or even a password confirmation for transactions above € 10?

**Comment by iasoon** [comment]
:+1: for a confirmation

**Comment by NoctuaNivalis** [comment]
All seem good ideas, and I would use them all. For instance:
- Transactions below €6 are completed without confirmation. (€6 being the price of a Chinese meal)
- Transactions above €6 require a simple confirmation. (So paying a pizza doesn't take too long)
- Transactions over €30 should perhaps be confirmed by the administrator? Zeus isn't your personal bank account.

**Comment by iasoon** [comment]
Keep in mind that adding debit to your account is a transaction as well, and will usually be more than 30 euries.Confirming all of these manually won't be fun.

Perhaps the best option would be to let an user set a 'pin code' that is needed to complete a transaciton, so that there is both a simple confirmation and a password protection that isn't a major annoyance for people who use strong passwords?

**Comment by feliciaan** [comment]
@iasoon: should the treasurer not add debit to your account, because (s)he needs to confirm that the transaction happened?

**Comment by iasoon** [comment]
Yes, @feliciaan. This is modelled as a transaction.

**Comment by NoctuaNivalis** [comment]
We could leave out the third condition for transactions by the admin, because he'd be the one to confirm it anyway.

A PIN-code sounds nice as well.
